name: Release

on:
  push:
    branches:
      - main
      - beta
jobs:
  checkCommit:
    name: Check commit
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - id: commit
        run: echo "message=${{ github.event.head_commit.message }}" >> $GITHUB_OUTPUT
    outputs:
      commitMsg: ${{ steps.commit.outputs.message }}
  release:
    name: Release
    needs: [checkCommit]
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for trusted publisher publishing
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 24
      - name: Install yarn
        run: |-
          NODE_ENV=development yarn
      - name: Test packages
        run: yarn test
      - name: Release packages
        if: "startsWith(needs.checkCommit.outputs.commitMsg, 'chore(release):')"
        env:
          NODE_ENV: production
        run: yarn lerna:publish
