name: Tests

on:
  pull_request:
    branches:
      - main
      - beta

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10.x', '12.x', '14.x' ]
    name: Node ${{ matrix.node }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        git remote set-branches --add origin main beta
        git fetch
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install Dependencies
      run: yarn install --immutable
      env:
        NODE_ENV: development
    - name: Build Packages
      run: yarn build
      env:
        NODE_ENV: development
    - name: Unit Tests
      run: yarn test:unit
      env:
        NODE_ENV: production
    - name: Git History Test
      run: yarn test:git-history
      env:
        NODE_ENV: production
    - name: Lint
      run: yarn lint
      env:
        NODE_ENV: production
